### ISSUE TITLE
yarn test fails with error `Cannot find module '@aws-sdk/util-dynamodb'`

### ISSUE THREAD

**Issue by trivikr** [trivikr/aws-sdk-client-mock-test#1]
### Steps to reproduce

Follow README.
Run `yarn test`

Output:
```console
Cannot find module '@aws-sdk/util-dynamodb' from 'node_modules/@aws-sdk/lib-dynamodb/dist/cjs/commands/utils.js'

    Require stack:
      node_modules/@aws-sdk/lib-dynamodb/dist/cjs/commands/utils.js
      node_modules/@aws-sdk/lib-dynamodb/dist/cjs/commands/BatchExecuteStatementCommand.js
      node_modules/@aws-sdk/lib-dynamodb/dist/cjs/index.js
      src/getUserNames.spec.ts
```

**Comment by m-radzikowski** [comment]
I don't think it's a problem with the `aws-sdk-client-mock` library.

When transpiling with `tsc` it seems to work fine, until you remove the `skipLibCheck: true` from the `tsconfig.json`. Without it, it fails with the same error.

I also tried to bundle it with esbuild:

```bash
esbuild src/getUserNames.ts --bundle --outfile=out.js --target=node14
```

and the result is the same error.

When you do `yarn install`, you get those warnings:

```
warning " > @aws-sdk/lib-dynamodb@3.21.0" has unmet peer dependency "@aws-sdk/smithy-client@^3.0.0".
warning " > @aws-sdk/lib-dynamodb@3.21.0" has unmet peer dependency "@aws-sdk/types@^3.0.0".
warning " > @aws-sdk/lib-dynamodb@3.21.0" has unmet peer dependency "@aws-sdk/util-dynamodb@^3.0.0".
warning " > aws-sdk-client-mock@0.5.3" has unmet peer dependency "@aws-sdk/types@^3.0.0".
```

When you check `node_modules`, the `smithy-client` and `types` are actually installed, but the `util-dynamodb` is not.

The `util-dynamodb` is referenced in `@aws-sdk/lib-dynamodb/dist/cjs/commands/utils.js` (as the stack in error shows) for marshalling and unmarshalling.

The `aws-sdk-client-mock` does not mock Commands, the code in them is executed as is.
